### ISSUE TITLE
Support sound null safety

### ISSUE THREAD

**Issue by davidpanic** [subosito/simple_gravatar#4]
https://dart.dev/null-safety/migration-guide

**Comment by jtkeyva** [comment]
+1 thanks

**Comment by davidpanic** [comment]
Too bad I already switched to [flutter_gravatar](https://pub.dev/packages/flutter_gravatar) since it seemed to be better maintained.

**Comment by brouwer** [comment]
@subosito

**Comment by subosito** [comment]
Thanks to @brouwer, I have published [v1.1.0](https://pub.dev/packages/simple_gravatar), which supports null safety.
